src/objects/Job_Application_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Job application settings, stores the email id to be notified when a new job application is submitted.</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Job Application Settings</label>
</CustomObject>

src/classes/JobApplicationTest.cls
@isTest
public class JobApplicationTest {

    //Creates a job application
    public static testmethod void testSubmit() {
        system.debug('JobApplicationTest.testSubmit - Start');

        //Create test data
        Contact contact = New Contact();
        contact.FirstName = 'ContactFirstName';
        contact.LastName = 'ContactLastName';
        contact.Email = 'ContactEmail@Email.com';
        //Create Custom settings record for notification email
        Job_Application_Settings__c setting = new Job_Application_Settings__c();
        setting.Name = 'NotificationEmail';
        setting.Value__c = 'testemail@test.com';
        insert setting;

        Test.startTest();
        ApexPages.StandardController stdController = new ApexPages.standardController(contact);
        JobApplicationControllerExt extController = new JobApplicationControllerExt(stdController);
        // Test save/submit method
        PageReference testPageResult = extController.save();
        Test.stopTest();

        Id contactId = extController.contact.Id;
        System.assertNotEquals(null, contactId);

        system.debug('JobApplicationTest.testSubmit - End');
    }

}