src/objects/Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Merchandise__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Merchandise</label>
        <referenceTo>Merchandise__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <label>Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestCleanUpBatchClass.cls
@isTest
public class TestCleanUpBatchClass {

    static testmethod void test() {
        //query use by the batch job
        String query = 'Select Id, CreatedDate From Merchandise__c Where Id not in (Select Merchandise__c From Line_Item__c)';
        
        //Create test merchandise items to be deleted by batch job
        Merchandise__c[] ml = new list<Merchandise__c>();
        for(integer i=0; i<10; i++) {
            Merchandise__c m= new Merchandise__c(Name='Batch Merchandise '+i, Description__c='Test', Price__c=2, Quantity__c=100);
            ml.add(m);
        }
        insert ml;
        
        Test.startTest();
        CleanUpRecords c = new CleanUpRecords(query);
        Database.executeBatch(c);
        Test.stopTest();
        
        //verify merchandise got deleted
        Integer i = [Select Count() From Merchandise__c];
        System.assertEquals(i, 0);
        
    }

}