src/objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MySchedulableClass.cls
global class MySchedulableClass implements Schedulable {

    global void execute(SchedulableContext ctx) {
        CronTrigger ct = [Select Id, CronExpression, TimesTriggered, NextFireTime From CronTrigger Where Id = :ctx.getTriggerId()];
        System.debug(ct.CronExpression);
        System.debug(ct.TimesTriggered);
        
        Merchandise__c m = new Merchandise__c(
        					Name='Scheduled Job Item',
            				Description__c='Created by the scheduler',
        					Price__c=10,
        					Quantity__c=500);
        insert m;
    }

}