src/objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MerchandiseManager.cls
@RestResource(urlMapping='/Merchandise/*')
global with sharing class MerchandiseManager {

    @HttpGet
    global static Merchandise__c getMerchandiseById() {
        RestRequest req = RestContext.request;
        String merchId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        Merchandise__c result = [Select Name, Description__c, Price__c, Quantity__c From Merchandise__c where Id= :merchId];
        return result;
    }
    
    @HttpPost
    global static String createMerchandise(String name, String description, Decimal price, Decimal quantity) {
        Merchandise__c m = new Merchandise__c(Name=name, Description__c=description, Price__c=price, Quantity__c=quantity);
        insert m;
        return m.Id;
    }
    
}