src/objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StoreFrontController.cls
public class StoreFrontController {

    List<DisplayMerchandise> products;
    List<DisplayMerchandise> shoppingCart = new List<DisplayMerchandise>();
    
    //Action method to handle purchasing process
    public PageReference addToCard() {
        for(DisplayMerchandise p : products) {
            if(0 < p.qtyToBuy) {
                shoppingCart.add(p);
            }
        }
        return null;    //stay on same page
    }
    
    public String getCartContents() {
        if(0 == shoppingCart.size()) {
            return '(empty)';
        }
        String msg = '<ul>\n';
        for(DisplayMerchandise p : shoppingCart) {
            msg += '<li>' + p.name + ' (' + p.qtyToBuy + ') ' + '</li>\n';
        }
        msg += '<ul>';
        return msg;
    }
    
    public List<DisplayMerchandise> getProducts() {
        if(products == null) {
            products = new List<DisplayMerchandise>();
            for(Merchandise__c item : [Select Id, Name, Description__c, Price__c, Quantity__c from Merchandise__c]) {
                products.add(new DisplayMerchandise(item));
            }
        }
        return products;
    }
    
    //Inner class to hold online store details for item
    public class DisplayMerchandise {
        private Merchandise__c merchandise;
        public DisplayMerchandise(Merchandise__c item) {
            this.merchandise = item;
        }
        
        //properties for use in Visualforce view
        public String name {
            get {return merchandise.Name; }
        }
        public String description {
            get {return merchandise.Description__c; }
        }
        public Decimal price {
            get {return merchandise.Price__c; }
        }
        public boolean inStock {
            get {return (0 < merchandise.Quantity__c); }
        }
        public Integer qtyToBuy { get; set;}
    }
    
    
}