src/objects/Site__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Site Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Site</label>
    <nameField>
        <displayFormat>S{000}</displayFormat>
        <label>Site Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Site_Part__c.object
<CustomObject>
    <fields>
        <fullName>Installation_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Installation Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>Site Parts</relationshipLabel>
        <relationshipName>Site_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inventory_Loc__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory Loc</label>
        <referenceTo>Inventory_Location__c</referenceTo>
        <relationshipLabel>Site Parts</relationshipLabel>
        <relationshipName>Site_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Site Part</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InventoryManagementWS.cls
global with sharing class InventoryManagementWS {
    webservice static String installSerial(String serialNo, String siteId) {
        System.debug('InventoryManagementWS.installSerial - Start');
        System.debug('InventoryManagementWS.installSerial: SiteId: ' + siteId 
                     + ' serialNo: ' + serialNo);
        list<Site__c> listSite = [SELECT Id FROM Site__c WHERE Name__c=:siteId];
        list<Site_Part__c> listSP = [SELECT Id FROM Site_Part__c WHERE Name=:serialNo];
        System.debug('InventoryManagementWS.installSerial - SOQL complete');
        if(listSite.size()==0) {
            System.debug('InventoryManagementWS.installSerial - Site Id Invalid');
            return 'Site Id Invalid';
        }
        if(listSP.size()==0) {
            System.debug('InventoryManagementWS.installSerial - Serial Number Invalid');
            return 'Serial Number Invalid';
        }
        System.debug('InventoryManagementWS.installSerial - Site and Serial Number found');
        listSP[0].Installation_site__c = listSite[0].Id;
        listSP[0].Inventory_Loc__c = null;
        update listSP[0];
        System.debug('InventoryManagementWS.installSerial - Success');
        return 'Success';
    }
}