src/objects/Site__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Site Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Site</label>
    <nameField>
        <displayFormat>S{000}</displayFormat>
        <label>Site Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Site_Part__c.object
<CustomObject>
    <fields>
        <fullName>Installation_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Installation Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>Site Parts</relationshipLabel>
        <relationshipName>Site_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Site Part</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestInventoryManagementWS.cls
@isTest
public class TestInventoryManagementWS {
    static testMethod void testInstallSerial() {
        System.debug('TestInventoryManagementWS.testInstallSerial - Start');
        Site__c site1 = New Site__c(Name__c='TestMethod Site 1');
        Site__c site2 = New Site__c(Name__c='TestMethod Site 2');
        list<Site__c> listSite = New list<Site__c>();
        listSite.add(site1);
        listSite.add(site2);
        insert listSite;
        System.debug('TestInventoryManagementWS.testInstallSerial - Site created');
        Site_Part__c sp = New Site_Part__c(Name='TST-111');
        sp.Installation_Site__c = site1.Id;
        insert sp;
        System.debug('TestInventoryManagementWS.testInstallSerial - Serial created');
        Test.startTest();
        System.debug('TestInventoryManagementWS.testInstallSerial - Inside startTest()');
        String response = '';
        response = InventoryManagementWS.installSerial(sp.Name, site2.Name__c);
        System.debug('TestInventoryManagementWS.testInstallSerial - response=' + response);
        Test.stopTest();
        System.debug('TestInventoryManagementWS.testInstallSerial - stopTest() complete');
        system.assertEquals('Success', response);
    }
}